# Generated by Django 6.0.3 on 2026-04-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (EN)')),
                ('deposit_type', models.CharField(choices=[('reservoir', 'Suv ombori'), ('lake', "Ko'l"), ('groundwater', 'Yer osti suvlari')], default='reservoir', max_length=20, verbose_name='Turi')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzoqlik')),
                ('radius_meters', models.FloatField(default=5000, verbose_name='Radius (metr)')),
                ('status', models.CharField(choices=[('normal', "✅ Me'yor"), ('warning', '⚠️ Ogohlantirish'), ('critical', '🚨 KRITIK')], default='normal', max_length=20, verbose_name='Holati')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
            ],
            options={
                'verbose_name': "Suv ob'yekti",
                'verbose_name_plural': "Suv ob'yektlari",
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Qurilma ID')),
                ('name', models.CharField(max_length=150, verbose_name='Post nomi')),
                ('canal_name', models.CharField(max_length=100, verbose_name='Kanal nomi')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzoqlik')),
                ('max_flow_rate', models.FloatField(default=10.0, verbose_name="Maks. o'tkazuvchanlik qobiliyati (m3/s)")),
                ('min_flow_rate', models.FloatField(default=0.5, verbose_name='Min. ruxsat etilgan oqim (m3/s)')),
                ('status', models.CharField(choices=[('normal', "✅ Me'yor"), ('warning', '⚠️ Ogohlantirish'), ('critical', '🚨 KRITIK')], default='normal', max_length=20, verbose_name='Joriy holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('upstream_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_sensors', to='core.sensor', verbose_name='Yuqori oqimdagi datchik')),
            ],
            options={
                'verbose_name': 'Datchik',
                'verbose_name_plural': 'Datchiklar',
            },
        ),
        migrations.CreateModel(
            name='Hydrometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Sana va vaqt')),
                ('flow_rate', models.FloatField(null=True, verbose_name='Suv sarfi (m3/s)')),
                ('water_level', models.FloatField(null=True, verbose_name='Suv sathi (m)')),
                ('ph_level', models.FloatField(default=7.0, null=True, verbose_name='pH darajasi')),
                ('turbidity', models.FloatField(null=True, verbose_name='Loyqalik (NTU)')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.sensor')),
            ],
            options={
                'verbose_name': "Gidroko'rsatkich",
                'verbose_name_plural': "Gidroko'rsatkichlar tarixi",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='Anomaliya turi')),
                ('severity', models.CharField(choices=[('info', 'ℹ️ Info'), ('warning', '⚠️ Ogohlantirish'), ('critical', '🚨 KRITIK')], default='warning', max_length=20, verbose_name='Daraja')),
                ('message', models.TextField(verbose_name='Anomaliya haqida xabar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Voqea sanasi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal qilindi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan sana')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.sensor')),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
