# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Устройства')),
                ('name', models.CharField(max_length=150, verbose_name='Название поста')),
                ('canal_name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('max_flow_rate', models.FloatField(default=10.0, verbose_name='Макс. пропускная способность (м3/с)')),
                ('min_flow_rate', models.FloatField(default=0.5, verbose_name='Мин. допустимый поток (м3/с)')),
                ('status', models.CharField(choices=[('normal', '✅ Норма'), ('warning', '⚠️ Предупреждение'), ('critical', '🚨 КРИТИЧНО')], default='normal', max_length=20, verbose_name='Текущий статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('upstream_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_sensors', to='sensors.sensor', verbose_name='Датчик выше по течению')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
            },
        ),
    ]
