# Generated by Django 6.0.3 on 2026-03-31 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Datchik', 'verbose_name_plural': 'Datchiklar'},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='canal_name',
            field=models.CharField(max_length=100, verbose_name='Kanal nomi'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(verbose_name='Uzoqlik'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_flow_rate',
            field=models.FloatField(default=10.0, verbose_name="Maks. o'tkazuvchanlik qobiliyati (m3/s)"),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_flow_rate',
            field=models.FloatField(default=0.5, verbose_name='Min. ruxsat etilgan oqim (m3/s)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Post nomi'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('normal', "✅ Me'yor"), ('warning', '⚠️ Ogohlantirish'), ('critical', '🚨 KRITIK')], default='normal', max_length=20, verbose_name='Joriy holat'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Qurilma ID'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='upstream_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_sensors', to='sensors.sensor', verbose_name='Yuqori oqimdagi datchik'),
        ),
    ]
