# Generated by Django 6.0.3 on 2026-04-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_options_alter_sensor_canal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('deposit_type', models.CharField(choices=[('reservoir', 'Suv ombori'), ('lake', "Ko'l"), ('groundwater', 'Yer osti suvlari')], default='reservoir', max_length=20, verbose_name='Turi')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzoqlik')),
                ('radius_meters', models.FloatField(default=5000, verbose_name='Radius (metr)')),
                ('status', models.CharField(choices=[('normal', "✅ Me'yor"), ('warning', '⚠️ Ogohlantirish'), ('critical', '🚨 KRITIK')], default='normal', max_length=20, verbose_name='Holati')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': "Suv ob'yekti",
                'verbose_name_plural': "Suv ob'yektlari",
            },
        ),
    ]
