# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='Тип аномалии')),
                ('severity', models.CharField(choices=[('info', 'ℹ️ Инфо'), ('warning', '⚠️ Предупреждение'), ('critical', '🚨 КРИТИЧНО')], default='warning', max_length=20, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение об аномалии')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-timestamp'],
            },
        ),
    ]
