# Generated by Django 6.0.3 on 2026-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Xabarnoma', 'verbose_name_plural': 'Xabarnomalar'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(max_length=50, verbose_name='Anomaliya turi'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Hal qilindi'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(verbose_name='Anomaliya haqida xabar'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan sana'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'ℹ️ Info'), ('warning', '⚠️ Ogohlantirish'), ('critical', '🚨 KRITIK')], default='warning', max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Voqea sanasi'),
        ),
    ]
