# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydrometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Дата и время')),
                ('flow_rate', models.FloatField(null=True, verbose_name='Расход воды (м3/с)')),
                ('water_level', models.FloatField(null=True, verbose_name='Уровень воды (м)')),
                ('ph_level', models.FloatField(default=7.0, null=True, verbose_name='pH уровень')),
                ('turbidity', models.FloatField(null=True, verbose_name='Мутность (NTU)')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Гидропоказание',
                'verbose_name_plural': 'История гидропоказаний',
                'ordering': ['-timestamp'],
            },
        ),
    ]
