# Generated by Django 6.0.3 on 2026-03-31 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_options_alter_sensor_canal_name_and_more'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrometry',
            options={'ordering': ['-timestamp'], 'verbose_name': "Gidroko'rsatkich", 'verbose_name_plural': "Gidroko'rsatkichlar tarixi"},
        ),
        migrations.AlterField(
            model_name='hydrometry',
            name='flow_rate',
            field=models.FloatField(null=True, verbose_name='Suv sarfi (m3/s)'),
        ),
        migrations.AlterField(
            model_name='hydrometry',
            name='ph_level',
            field=models.FloatField(default=7.0, null=True, verbose_name='pH darajasi'),
        ),
        migrations.AlterField(
            model_name='hydrometry',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='sensors.sensor'),
        ),
        migrations.AlterField(
            model_name='hydrometry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Sana va vaqt'),
        ),
        migrations.AlterField(
            model_name='hydrometry',
            name='turbidity',
            field=models.FloatField(null=True, verbose_name='Loyqalik (NTU)'),
        ),
        migrations.AlterField(
            model_name='hydrometry',
            name='water_level',
            field=models.FloatField(null=True, verbose_name='Suv sathi (m)'),
        ),
    ]
